name: Deploy to AWS Lambda

on:
  push:
    branches:
      - develop  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.13
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

     # Step 3: Install Python dependencies into build/ folder
      - name: Install dependencies
         run:|
          mkdir -p build
          pip install --upgrade pip
          pip install -r requirements.txt -t build
          cp -r main.py app build/  # ONLY copy what's needed
          

      # # Step 3: Zip the code for Lambda deployment
      # - name: Zip Lambda Function
      #   run: zip -r function.zip . -x "*.git*"

      - name: Zip Lambda Function
        run: |
          cd build
          zip -r ../function.zip .

      - name: Show ZIP contents
        run: unzip -l function.zip | grep mangum

      - name: Install AWS CLI
        run: |
          pip install awscli      

      # Step 4: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          function-name: "transcribelambda"  # Replace with your Lambda function name
          zip-file: "function.zip"
        run: |
          aws lambda update-function-code \
            --function-name transcribelambda \
            --region 'ap-south-1' \
            --zip-file fileb://function.zip
