name: Deploy to AWS Lambda

on:
  push:
    branches:
      - develop  # Trigger workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed)
      - name: Install Dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

       # Step 3: Install Python dependencies into build/ folder
      - name: Install dependencies
        run: |
          mkdir -p build
          pip install -r requirements.txt -t build
          cp -r main.py api core services utils build/

      # Step 3: Zip the code for Lambda deployment
      - name: Zip Lambda Function
        run: zip -r function.zip . -x "*.git*"

      # Step 4: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"  # Replace with your AWS region
          function-name: "transcribelambda"  # Replace with your Lambda function name
          zip-file: "function.zip"
